# Generated by Django 4.0.4 on 2022-11-09 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('position', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'planned'), ('cancelled', 'cancelled'), ('in progress', 'in progress'), ('interrupted', 'interrupted'), ('closed', 'closed')], default='planned', max_length=20)),
                ('manager_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_game_studio.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('release_datetime', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_game_studio.project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('profile', models.CharField(choices=[('management', 'management'), ('finance', 'finance'), ('creative', 'creative'), ('hr', 'hr'), ('development', 'development'), ('design', 'design'), ('testing', 'testing')], default='development', max_length=20)),
                ('teams', models.ManyToManyField(to='db_game_studio.team')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('employee', models.ManyToManyField(to='db_game_studio.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_game_studio.project')),
                ('version_completed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_completed', to='db_game_studio.version')),
                ('version_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_created', to='db_game_studio.version')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_game_studio.team'),
        ),
    ]
