# Generated by Django 4.0.4 on 2022-11-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_game_studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teams',
            new_name='slave_teams',
        ),
        migrations.AlterField(
            model_name='project',
            name='manager_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_game_studio.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='version_completed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_completed', to='db_game_studio.version'),
        ),
    ]
