# Generated by Django 4.0.4 on 2022-11-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_game_studio', '0002_rename_teams_team_slave_teams_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='team',
            name='slave_teams',
        ),
        migrations.AddField(
            model_name='team',
            name='master_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_game_studio.team'),
        ),
    ]
