# Generated by Django 4.0.4 on 2022-11-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_game_studio', '0003_rename_manager_id_project_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_game_studio.project'),
        ),
    ]
