# Generated by Django 4.1.3 on 2022-11-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_game_studio', '0005_alter_task_description_alter_task_version_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task_number',
            field=models.IntegerField(default=0),
        ),
    ]
