# Generated by Django 4.0.4 on 2022-12-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_game_studio', '0006_employee_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='db_game_studio.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='version_completed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='version_completed', to='db_game_studio.version'),
        ),
        migrations.AlterField(
            model_name='task',
            name='version_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='version_created', to='db_game_studio.version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='db_game_studio.project'),
        ),
    ]
